"Common properties in ArmorStand"
armorstand_version = "0.0.10"
home_page = "https://github.com/TouchController/TouchController"
sources_page = "https://github.com/TouchController/TouchController"
issue_tracker = "https://github.com/TouchController/TouchController/issues"
license = "LGPL-3.0-or-later"
